# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todos_pb2 as todos__pb2


class TodosStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTodos = channel.unary_unary(
        '/grpc.Todos/GetTodos',
        request_serializer=todos__pb2.Request.SerializeToString,
        response_deserializer=todos__pb2.Response.FromString,
        )


class TodosServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTodos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodosServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTodos': grpc.unary_unary_rpc_method_handler(
          servicer.GetTodos,
          request_deserializer=todos__pb2.Request.FromString,
          response_serializer=todos__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.Todos', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
